# Copyright 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
runtime: go111

handlers:
- url: /_cron/.*
  script: auto
  secure: always
  login: admin

- url: /admin/.*
  script: auto
  secure: always
  login: admin

- url: /internal/.*
  script: auto
  secure: always
  login: admin

- url: /view.*
  script: auto
  secure: always
  login: admin

- url: /.*
  script: auto

