application: chromium-committers
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0

handlers:

# Endpoints handler.
- url: /_ah/api/.*
  script: appengine_module.chromium_committers.app.ep_server

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always

- url: /.*
  script: appengine_module.chromium_committers.app.app
  secure: always


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- tests/(.*/)?.*
