application: test-results-hrd
service: default
runtime: go111
instance_class: F4_1G
automatic_scaling:
  max_concurrent_requests: 4

handlers:
  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt
    secure: always

  - url: /images
    static_dir: static/images
    secure: always

  - url: /stylesheets
    static_dir: static/stylesheets
    secure: always

  - url: /dashboards
    static_dir: static/dashboards
    secure: always

  - url: /src
    static_dir: src
    secure: always

  - url: /bower_components
    static_dir: bower_components
    secure: always

  - url: /internal/.*
    script: auto
    login: admin
    secure: always

  - url: /.*
    script: auto
    secure: always
