# Push queues
queue:
- name: analyze-queue
  mode: push
  rate: 1/s
  retry_parameters:
    task_retry_limit: 10
- name: driver-queue
  mode: push
  rate: 500/s
  retry_parameters:
    task_retry_limit: 10
- name: gerrit-reporter-queue
  mode: push
  rate: 1/s
  retry_parameters:
    task_retry_limit: 10
- name: launcher-queue
  mode: push
  rate: 1/s
  retry_parameters:
    task_retry_limit: 10
- name: poll-project-queue
  mode: push
  rate: 10/s
  retry_parameters:
    task_retry_limit: 10
- name: tracker-queue
  mode: push
  rate: 1/s
  retry_parameters:
    task_retry_limit: 10

# Pull queues
- name: bigquery-analysis-results-queue
  mode: pull
- name: bigquery-feedback-events-queue
  mode: pull
