runtime: go113

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/master/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  chops-rotation-proxy-test:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  chrome-ops-rotation-proxy:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
entrypoint: >
  main -auth-service-host ${AUTH_SERVICE_HOST}

handlers:
- url: /.*
  script: auto
  secure: always
