runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10m"

handlers:
- url: /(.+.ico)
  static_files: static/\1
  mime_type: image/x-icon
  upload: static/(.+.ico)
  expiration: "1h"

- url: /(robots\.txt)
  static_files: static/\1
  mime_type: text/plain
  upload: static/(robots\.txt)

- url: /mailer/.*
  script: mailer.app
  secure: always

- url: /.*
  script: handler.application

includes:
- gae_ts_mon  # handles /internal/cron/ts_mon/send

libraries:
- name: django
  version: 1.2
- name: jinja2
  version: 2.6

builtins:
- appstats: on
- deferred: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- tests/(.*/)?.*
