runtime: go113
service: default

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/master/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  unified-fleet-system-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  unified-fleet-system-staging:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  unified-fleet-system-prod:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com

# Following https://groups.google.com/a/google.com/g/prometheus-discuss/c/vIZLu2hMPGY/m/ddK-5K0xBwAJ
# switch to use `main -flag value` instead of `/usr/local/bin/start`
entrypoint: >
    main -auth-service-host ${AUTH_SERVICE_HOST}
